1. this が変わる場合

- new がついた時

```js
function Human(name) {
  this.name = name;
}

new Human("Jin");
// this.name => Jin
```

- object の中の関数で呼ばれた時

```js
const obj = {
  name: "Jin",
  sayName() {
    console.log(this.name);
  },
  //上のと同じ
  //sayName: function(){
  //    console.log(this.name)
  //}
};

obj.sayName(); // Jin

// アロー関数は違う
const obj = {
  name: "Jin",
  sayName: () => {
    console.log(this.name);
  },
};

obj.sayName(); // '' <= window.nameと同じ
```

- bind, apply, call

```js
function sayName() {
  console.log(this.name);
}

sayName(); // window.nameなので ''が出力される

sayName.bind({ name: "Jin" })(); // Jin
// bindは関数呼び出しまでつける必要がある
sayName.apply({ name: "Jin" }); // Jin
// applayは関数呼び出しまで合わせる
sayName.call({ name: "Jin" }); // Jin
```

- 参照

```js
function add(a, b) {
  return a + b;
}
add.apply(null, [3, 5]); // nullと書いてる部分はthisが入る位置なんですが、今はthisがないので、何が入っても問題ない
add.call(null, 3, 5); // nullは同じくthisの位置
// 違いはapplyは配列でまとめてa,bに入れる、callはそのままa,bに入れる
```

- check

```js
const obj = {
  name: "Jin",
  sayName() {
    console.log(this.name);
    function inner() {
      console.log(this.name);
    }
    inner();
  },
};

obj.sayName();
// Jin <- obj.sayNameなので、
//　　　　　　　　　　<- inner()を呼ぶとき何もついてないのでwindow.nameを呼ぶ

const obj = {
  name: "Jin",
  sayName() {
    console.log(this.name);
    const inner = () => {
      console.log(this.name);
    };
    inner();
  },
};

obj.sayName();
// Jin
// Jin <- arrow functionは親のthisを参照するのでwindow.nameではない

const obj = {
  name: "Jin",
  sayName() {
    console.log(this.name);
    const inner = () => {
      console.log(this.name);
    };
    inner.call(obj);
  },
};

obj.sayName();
// Jin
// Jin  <- callでthisを変えたのでobjのnameが出る
```

this を呼び出される時に決まる、なので上のコードで sayName()の this は何か言えない

2. callback, promise
   callback は結果の値をすぐもらわなければいけない
   (ただ見づらいから悪いっていうこどではなかった、、)

```js
axios.get("server1", function(data1){
    axios.get("server2", function(data2){
        axios.get("server3", function(data3){
            ...
        })
    })
})
```

promise は結果の値を今すぐもらわなくてもいい
後で、まとめてもらえる

```js
const p1 = axios.get("server1");
const p2 = axios.get("server2");
const p3 = axios.get("server3");
const p4 = axios.get("server4");
const p5 = axios.get("server5");
const p6 = axios.get("server6");

// 他の作業をして

Promise.all([p1, p2, p3, p4, p5, p6]).then((result) => {});
// ここで貰おうとなったらもらえる

Promise.all([p1, p2, p3, p4, p5, p6])
  .then((result) => {})
  .catch((error) => {});
// しかし、p1 ~ P6の中で一個でも問題が発生したら全部使えなくなる
// しかも、ただerror messageだけ出るので何番目で失敗したかわからない

// それで出たのがallSettled
Promise.allSettled([p1, p2, p3, p4, p5, p6])
  .then((result) => {
    // 失敗したのだけfillteringしてretry
  })
  .catch((error) => {});
```

- 同時に実行されても優先順位が違う

```js
// 即時実行
setImmediate(() => {
  console.log("a");
});

setTimeout(() => {
  console.log("b");
}, 1000);

setTimeout(() => {
  console.log("c");
}, 2000);

Promise.resolve().then(() => {
  console.log("p");
});

//実行順
// p
// a
// b
// c
```

promise, process.nextTick は他のものよりさっきに実行される

- 分析

```js
let a = 2;

const p = new Promise((resolve, reject) => {
  // この部分は同期
  console.log("first");
  setTimeoust(() => {
    a = 5;
    console.log(a);
    resolve(a); // promiseはresolveが実行された時、stackに入る
  }, 0);
});

// 1
console.log("2");
// 3
p.then((result) => {
  // resolveが呼ばれた時、resultと繋がる
  console.log("result", result);
});

// first
// 2
// 5
// result 5
```
