- 非同期

- then/catch の場合

```js
p.then((result) => {
  console.log("result", result);
})
  .then(() => {
    // error　発生
  })
  .then(() => {})
  .then(() => {})
  .then(() => {})
  .catch((error) => {
    //  ここで処理
    console.error(error);
  })
  .finally(() => {});
```

then で error が発生すると catch で表示する
catch は p.then から catch の上にある then まで担当する

下記のような形も可能

```js
p.then((result) => {
  console.log("result", result);
})
  .catch(() => {})
  .then(() => {
    // error　発生
  })
  .catch((e) => {
    // ここで処理
    console.error(e);
  })
  .then(() => {})
  .catch(() => {})
  .then(() => {})
  .catch(() => {})
  .then(() => {})
  .catch(() => {})
  .finally(() => {});
```

各々の catch が各々の then を担当しているので
最後の catch が一つしかなかった時より最後の catch の負担が少なくなる

- try/catch の場合

```js
function delayP(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms);
    reject(error);
  });
}

async function a() {
  try {
    // ここのエラーは他のawaitと別途処理
    await delayP(1000);
  } catch (error) {
    console.log(error);
  }

  try {
    await delayP(1000);
    await delayP(1000);
    await delayP(1000);
  } catch (error) {
    console.log(error);
  }
}
```

- promise に関してもっと詳しく

  - then/catch の場合

  ```js
  p.then((result) => {
    console.log("result", result);
    return 1;
  })
    .then((result) => {
      console.log(result); // 1 <- 前でもらったreturn値がresultに入ってくる
    })
    .then((result) => {
      console.log(result); // undefined <- 前のreturnがないのでundefinedが出力される
      return Promise.resolve(1);
    })
    .then((result) => {
      console.log(result); // Promise.resolve(1)ではなくresolveされた値が出力される
      // Promiseではなく一般的な値だったらそのまま次のresultに伝わる
    })
    .then(() => {})
    .catch(() => {})
    .finally(() => {});
  ```

  - async/await の場合

  ```js
  async function a() {
    const a = await 1; // このまま1が変数aに入る
    const b = await Promise.resolve(1); // resolveされた値が変数bに入る
  }
  ```

- async/await & Promise 変換

```js
async function a() {
  const a = await 1; // 1が同期でもawaitがついてたら非同期になる
  console.log("a", a);
  console.log("hmm");
  await null;
  const b = await Promise.resolve(1);
  console.log("b", b);
  return b;
}

Promise.resolve(1)
  .then((a) => {
    console.log("a", a);
    console.log("hmm");
    return null;
  })
  .then(() => {
    return Promise.resolve(1);
  })
  .then((b) => {
    console.log("b", b);
    return b;
  });
```

- 実行順番

```js
async function a() {
  console.log("2");
  const a = await 1;
  console.log("4");
  console.log("a", a);
  console.log("hmm");
  await null;
  const b = await Promise.resolve(1);
  console.log("b", b);
  return a + b;
}

console.log("1");
a()
  .then((result) => {
    console.log(result);
  })
  .then((result) => {
    console.log(result2);
  });
console.log("3");

// 1
// 2
// 3
// 4
// a 1
// hmm
// b 1
// 2
// undefiend
```
